{% set name = "ipcoal" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eaton-lab/ipcoal/archive/{{ version }}.tar.gz
  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - numba
    - toytree
    - toyplot
    - requests
    - future
    - msprime

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipcoal

about:
  home: https://github.com/eaton-lab/ipcoal
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Multispecies coalescent simulation, visualization, and analysis in Python
  description: |
    A minimalist library for simulating and analyzing genealogies
    and sequences across genomes in a phylogenetic context.
  doc_url: https://eaton-lab.org/ipcoal
  dev_url: https://github.com/eaton-lab/ipcoal

extra:
  recipe-maintainers:
    - eaton-lab
    - pmckenz1
