{% set name = "ipcoal" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eaton-lab/ipcoal/archive/{{ version }}.tar.gz
  sha256: 0a5bfcfe513b55ac6138204dd327e03f45eaa20565cdbe111433d909053e29e1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - numba
    - toytree
    - toyplot
    - requests
    - future
    - msprime

test:
  imports:
    - ipcoal

about:
  home: https://github.com/eaton-lab/ipcoal
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Coalescent simulations in Python
  description: |
    A minimalist library for simulating and analyzing genealogies
    and sequences across genomes in a phylogenetic context.
  doc_url: https://ipcoal.readthedocs.io/
  dev_url: https://github.com/eaton-lab/ipcoal

extra:
  recipe-maintainers:
    - eaton-lab
    - pmckenz1
